debug: false
database:
  type: 'sqlite' # Types: sqlite, mysql
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: ''
autopurge:
  days: 90 # automatically remove accounts not logged since x days, 0 to disable
title:
  enabled: true
  messages:
    login: '&7/login <password>'
    register: '&7/register <password> <confirm_password>'
    logged: '&aYou have successfully logged in.'
    registered: '&aYou have successfully registered.'
features:
  experience-bar: true
  pumpkin: true
auth:
  premium: false
  max-accounts: 5
sessions:
  enabled: true
  duration: 1440 # duration in minutes
permissions:
  admin: 'kauth.admin'
messages:
  usage: ' &8>> &cCorrect command usage: &7{USAGE}&c.'
  login-usage: '/login <password>'
  register-usage: '/register <password> <confirm_password>'
  change-password-usage: '/changepassword <old_password> <new_password>'
  cant-use-in-console: '&cYou cannot use this command in console.'
  cant-use-as-premium: ' &8>> &cYou cannot use this command as premium player.'
  logged: ' &8>> &aYou have successfully logged in.'
  logged-premium: ' &8>> &aYou have been automatically logged in. &7(premium account)'
  changed: '&8>> &aPassword successfully changed.'
  registered: ' &8>> &aYou have successfully registered.'
  unregistered: ' &8>> &aYou have successfully unregistered.'
  logout: ' &8>> &aYou have successfully logged out.'
  register: '&8>> &cRegister using the command &7/register <password> <repeat_password>&c.'
  login: ' &8>> &cLog in using the command &7/login <password>&c.'
  session: ' &8>> &aYou have been automatically logged in. &7(login session)'
  wrong-password: ' &8>> &cThe password provided is &7incorrect&c.'
  not-registered: ' &8>> &cYour account is not &7registered&c.'
  not-logged: ' &8>> &cYou are not &7logged in&c.'
  already-registered: ' &8>> &cYour account is already registered, please log in.'
  already-logged: ' &8>> &cYou are already &7logged in&c.'
  not-same-password: ' &8>> &cThe passwords provided do not match.'
  correct-username: ' &8>> &cYour correct username: &7{NAME}'
  invalid-characters: ' &8>> &cYour password must be between &74 and 32 characters long &cand consist of the following characters: &7a-ZA-Z0-9.'
  invalid-username: ' &8>> &cYour username contains invalid characters.'
  no-perm: ' &8>> &cYou do not have &7permission &cto use this &7command&c.'
  max-accounts: ' &8>> &cYou have reached the maximum number of accounts for your IP.'
  time-left: '&8>> &cYour time to log in has expired.'
listeners:
  move: true