name: KAuth
version: 1.0.1-SNAPSHOT
api-version: 1.13
authors: [kuezese]
main: pl.kuezese.auth.spigot.SpigotPlugin
commands:
 login:
  aliases: [log, l]
 register:
  aliases: [reg, r]
 changepassword:
  aliases: [changepass]
 logout:
  aliases: [logoff]
 auth: