name: KAuth
version: 1.0.2-SNAPSHOT
api-version: 1.13
authors: [kuezese]
main: pl.kuezese.auth.spigot.SpigotPlugin
depend: [TitleAPI]

commands:
 login:
  aliases: [log, l]
 register:
  aliases: [reg, r]
 changepassword:
  aliases: [changepass]
 logout:
  aliases: [logoff]
 auth: